name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build release artifacts
      run: cargo build --release
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      if: matrix.os == 'windows-latest'
      with:
        name: ed-rs-${{ matrix.os }}
        path: target/release/ed-rs.exe
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      if: matrix.os != 'windows-latest'
      with:
        name: ed-rs-${{ matrix.os }}
        path: target/release/ed-rs
